 [package]
name = "Solcipher"
version = "1.0.0"
authors = ["Your Name <you@example.com>"]

[addresses]
solcipher = "_"   # Will be replaced on publish

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "aptos-mainnet" }

[dev-dependencies]

[dev-addresses]
